USE NORTHWIND

******************************************************************************************************************************************************************************************
SELECT TOP 10 * FROM DBO.CUSTOMERS

SELECT
FIRSTNAME+' '+LASTNAME CONTACT_NAME, ADDRESS, CITY FROM EMPLOYEES
UNION
SELECT CONTACTNAME, ADDRESS, CITY FROM CUSTOMERS
******************************************************************************************************************************************************************************************
UPDATE CUSTOMERS
SET REGION = 'EASTERN EUROPE'
WHERE COUNTRY LIKE 'G%'

SELECT * FROM CUSTOMERS
WHERE COUNTRY LIKE 'G%'

******************************************************************************************************************************************************************************************
--CAST VARIABLES TO DIFFERENT TYPES
DECLARE @SAMPLETEXT AS VARCHAR(10);
SET @SAMPLETEXT = '123456';

DECLARE @REALDATE AS VARCHAR(10);
SET @REALDATE = '13/09/2023';

SELECT TRY_CONVERT(INT,@SAMPLETEXT);
SELECT TRY_CONVERT(DATETIME,@SAMPLETEXT);
SELECT TRY_CONVERT(DATE,@REALDATE,111);
SELECT TRY_CAST(@REALDATE AS DATE)

DECLARE @A VARCHAR(2)--DON'T FORGET PUT THE TYPE OF THE VARIABLE TO CREATE
DECLARE @B VARCHAR(2)
SET @A = '2'
SET @B = '4'
SELECT CAST(@A AS INT) + CAST(@B AS INT) AS RESULT
SELECT CONVERT(VARCHAR(20),GETDATE(),108)

--OFFSET SHOWS ROWS THAT CONTINUES AFTER THE NUMBER
SELECT * FROM CUSTOMERS
ORDER BY CUSTOMERID
OFFSET 50 ROWS

DECLARE @WW INT
SET @WW = 17
SELECT @WW AS V1, @WW+2 AS V2, 'NULL' AS V3

--PRACTICE FOR NULL 
SELECT
CITY,COUNTRY,ISNULL(REGION,'SIN REGION')
FROM CUSTOMERS
WHERE REGION IS NULL
ORDER BY COUNTRY

--REMEMBER THE TABLE OF CODES TO GET THE SPECIFIC FORMAT OF DATE
SELECT CONVERT(VARCHAR(30),GETDATE(),100) AS CURRENTDATE

--REMEMBER THE FORMAT'S ARGUMENT
DECLARE @TODAY DATETIME = GETDATE()
SELECT FORMAT(@TODAY,N'F')

DECLARE @BDAY DATETIME='2023/02/22'
SELECT FORMAT(DATEADD(YEAR,1,@BDAY),N'F')

DECLARE @BDAY DATETIME='1989/02/22'
SELECT DATEDIFF(YEAR,@BDAY,GETDATE()) AS YEARSOLD

--COALESCE EXAMPLE

SELECT
CONTACTNAME,
COALESCE(PHONE,FAX) AS CONTACT_NUMBER
FROM CUSTOMERS
******************************************************************************************************************************************************************************************

USE NORTHWIND
SELECT * FROM INFORMATION_SCHEMA.TABLES;
SELECT * FROM CUSTOMERS;
SELECT * FROM FN_VIRTUALSERVERNODES()
--PAGE 65